# Generated by Django 6.0.7 on 2026-07-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaydevice',
            name='agent_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='client_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='has_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='hostname',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='hotspot_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='hotspot_ssid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='share_mode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='uplink_alias',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='uplink_ipv4',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='uplink_profile',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
