# Generated by Django 6.0.7 on 2026-07-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_gatewaydevice_agent_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaydevice',
            name='ipv6_leak_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='nat_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='privacy_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='privacy_shield_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='uplink_mac',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
