# Generated by Django 6.0.7 on 2026-07-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_gatewaydevice_ipv6_leak_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaydevice',
            name='client_isolation_active',
            field=models.BooleanField(default=False),
        ),
    ]
