# Generated by Django 6.0.7 on 2026-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_gatewaydevice_client_isolation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaydevice',
            name='gateway_lan_ip',
            field=models.CharField(blank=True, default='192.168.137.1', max_length=64),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='hotspot_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
